import type { Service } from "~/types/service";

export const SERVICES: Service[] = [
  {
    id: 1,
    category_id: 1,
    category_name: "Development",
    category_slug: "development",
    name: "Web Development",
    slug: "web-development",
    description:
      "Membangun website berkinerja tinggi dengan teknologi terbaru. Dari landing page estetik hingga sistem web kompleks yang skalabel.",
    icon: "Globe",
    image_path: "https://picsum.photos/id/1/1400/1200",
    is_active: true,
    order: 1,
    prices: [
      {
        id: 1,
        package_name: "Starter Site",
        price: "Rp 3.500.000",
        description: "Ideal untuk personal branding atau UMKM.",
        features: [
          "Responsive Design",
          "3-5 Halaman",
          "SEO Basic",
          "Analytics Integration",
          "Revisi 2x"
        ],
        is_active: true,
        order: 1,
      },
      {
        id: 2,
        package_name: "Business Pro",
        price: "Rp 8.000.000",
        description: "Solusi lengkap untuk bisnis yang sedang tumbuh.",
        features: [
          "CMS Integration (Wordpress/Sanity)",
          "10-15 Halaman",
          "SEO Advanced",
          "Kecepatan Optimasi",
          "Revisi 5x"
        ],
        is_active: true,
        order: 2,
      },
      {
        id: 3,
        package_name: "Custom System",
        price: "Start from Rp 15.000.000",
        description: "Sistem web custom sesuai kebutuhan spesifik.",
        features: [
          "Full Custom Code (Laravel/Nuxt)",
          "Database Design",
          "API Integration",
          "High Security",
          "Maintenance 3 Bulan"
        ],
        is_active: true,
        order: 3,
      },
    ],
  },
  {
    id: 2,
    category_id: 2,
    category_name: "Mobile",
    category_slug: "mobile",
    name: "Mobile App Development",
    slug: "mobile-app",
    description:
      "Aplikasi mobile native atau hybrid yang intuitif. Membawa bisnis Anda ke genggaman pelanggan dengan pengalaman pengguna terbaik.",
    icon: "Smartphone",
    image_path: "https://picsum.photos/id/119/1400/1200",
    is_active: true,
    order: 2,
    prices: [],
  },
  {
    id: 3,
    category_id: 3,
    category_name: "Design",
    category_slug: "design",
    name: "UI/UX Design",
    slug: "ui-ux-design",
    description:
      "Perancangan antarmuka yang memanjakan mata dan mudah digunakan. Kami fokus pada User Experience yang meningkatkan konversi.",
    icon: "Palette",
    image_path: "https://picsum.photos/id/180/1400/1200",
    is_active: true,
    order: 3,
    prices: [],
  },
  {
    id: 4,
    category_id: 4,
    category_name: "Consulting",
    category_slug: "consulting",
    name: "IT Consulting",
    slug: "it-consulting",
    description:
      "Bingung mulai dari mana? Konsultasikan kebutuhan teknologi Anda bersama ahli kami untuk strategi digital yang tepat sasaran.",
    icon: "BotMessageSquare",
    image_path: "https://picsum.photos/id/60/1400/1200",
    is_active: true,
    order: 4,
    prices: [],
  },
  {
    id: 5,
    category_id: 5,
    category_name: "Digital",
    category_slug: "digital",
    name: "Digital Marketing",
    slug: "digital-marketing",
    description:
      "Tingkatkan jangkauan bisnis Anda dengan strategi pemasaran digital terukur, mulai dari manajemen sosial media hingga ads.",
    icon: "TrendingUp",
    image_path: "https://picsum.photos/id/3/1400/1200",
    is_active: true,
    order: 5,
    prices: [],
  },
];
